apiVersion: v1
kind: Service
metadata:
  name: im-service
  namespace: default
  labels:
    app: im-service
spec:
  type: ClusterIP
  ports:
  - port: 9094
    targetPort: 9094
    protocol: TCP
    name: grpc
  selector:
    app: im-service
