apiVersion: v1
kind: Service
metadata:
  name: im-service
  namespace: default
  labels:
    app: im-service
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9094
    targetPort: 9094
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: im-service
