apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - im-service-deployment.yaml
  - im-service-service.yaml

commonLabels:
  app.kubernetes.io/part-of: im-chat-system
  app.kubernetes.io/name: im-service
  app.kubernetes.io/component: message-routing
