apiVersion: v1
kind: ConfigMap
metadata:
  name: {{SERVICE_NAME}}-config
  namespace: default
  labels:
    app: {{SERVICE_NAME}}
    component: backend
data:
  application.yml: |
    grpc:
      server:
        port: {{GRPC_PORT}}
    
    spring:
      application:
        name: {{SERVICE_NAME}}
    
    logging:
      level:
        root: INFO
        {{PACKAGE_NAME}}: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: when-authorized
