apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: default
  labels:
    app: {{SERVICE_NAME}}
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: {{GRPC_PORT}}
    targetPort: {{GRPC_PORT}}
    protocol: TCP
    name: grpc
  selector:
    app: {{SERVICE_NAME}}
  sessionAffinity: None
