apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-service-deployment.yaml
  - auth-service-service.yaml

commonLabels:
  app.kubernetes.io/part-of: im-chat-system
  app.kubernetes.io/name: auth-service
  app.kubernetes.io/component: authentication
