apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-service-deployment.yaml
  - user-service-service.yaml

commonLabels:
  app.kubernetes.io/part-of: im-chat-system
  app.kubernetes.io/name: user-service
  app.kubernetes.io/component: user-management
