apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - todo-service-deployment.yaml
  - todo-service-service.yaml

commonLabels:
  app.kubernetes.io/part-of: monorepo-services
  app.kubernetes.io/name: todo-service
